services:
  - type: web
    name: random-video-chat     # Xizmat nomi Render.com’da ko‘rinadi
    env: node                   # Muhit: Node.js
    nodeVersion: 22.14.0        # (ixtiyoriy) aniq Node versiyasini belgilash
    region: oregon              # Server manzili (frankfurt ham mumkin)
    plan: free                  # Bepul tarif
    branch: main                # GitHub’dagi asosiy branch nomi
    buildCommand: npm install   # Build bosqichi
    startCommand: node server.js # Serverni ishga tushirish
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true            # main’ga har pushda avtomatik deploy
